version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
